### ISSUE TITLE
Use `cargo clippy` instead of the clippy plugin

### ISSUE THREAD

**Issue by oli-obk** [Wilfred/remacs#757]
We're planning on removing the clippy plugin interface, because rustc will remove it someday anyway. All that is required on your end is to remove the clippy feature and replace all cfgs that depend on it with the `cargo-clippy` feature which is automatically enabled by cargo clippy.

So you can then use `cargo clippy` instead of `cargo build --features=clippy`. Note that cargo clippy requires a `cargo install clippy` first.

**Comment by shaleh** [comment]
clippy requires really recent nightly as remacs does not compile with current nightly. As soon as remacs does this issue can be looked at.

**Comment by shaleh** [comment]
```
    - rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
```
